name: Compile, test, and package (using Maven)

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java: [ '8', '11', '13' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build and run/test on ${{ matrix.os }} with ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
